--
manifests:
  - release-name: elastic-runtime  # pivnet release 1.6.16
    deployment-name: elastic-runtime
    release-number: "2046"
    file-number: "5411"
    stemcell: "https://bosh.io/d/stemcells/bosh-azure-hyperv-ubuntu-trusty-go_agent?v=3232.13"
    file: elastic-runtime.yml
    errands:
     - smoke-tests
     - push-apps-manager
     - autoscaling
     - autoscaling-register-broker
