---
manifests:
  - release-name: elastic-runtime  # pivnet release 1.6.16
    deployment-name: elastic-runtime
    release-number: "1485"
    file-number: "3888"
    stemcell: "https://bosh.io/d/stemcells/bosh-azure-hyperv-ubuntu-trusty-go_agent"
    file: elastic-runtime.yml
    errands:
     - smoke-tests
     - push-apps-manager
     - push-app-usage-service
     - notifications
     - notifications-tests
     - notifications-ui
     - notifications-ui-tests
     - autoscaling
     - autoscaling-register-broker
     - autoscaling-tests

  - release-name: p-mysql
    deployment-name: p-mysql
    release-number: "1509"
    file-number: "3930"
    stemcell: "https://bosh.io/d/stemcells/bosh-azure-hyperv-ubuntu-trusty-go_agent"
    file: p-mysql.yml
    errands:
     - broker-registrar
     - acceptance-tests

  - release-name: pivotal-rabbitmq-service
    deployment-name: p-rabbitmq
    release-number: "1523"
    file-number: "3962"
    stemcell: "https://bosh.io/d/stemcells/bosh-azure-hyperv-ubuntu-trusty-go_agent"
    file: p-rabbitmq.yml
    errands:
     - broker-registrar
     - acceptance-tests
