---
manifests:
  - release-name: elastic-runtime  # pivnet release 1.6.16
    deployment-name: elastic-runtime
    release-number: "2134"
    file-number: "5888"
    stemcell: "https://bosh.io/d/stemcells/bosh-azure-hyperv-ubuntu-trusty-go_agent?v=3232.17"
    file: elastic-runtime.yml
    errands:
     - smoke-tests
     - push-apps-manager

  - release-name: concourse
    deployment-name: concourse
    release-number: "1.6.0"
    file-number: "0"
    stemcell: "https://bosh.io/d/stemcells/bosh-azure-hyperv-ubuntu-trusty-go_agent"
    file: concourse.yml
