---

resources:

- name: github-release
  type: github-release
  source:
    user: cf-platform-eng
    repository: bosh-azure-template
    access_token: {{github-access-token}}

- name: github-repo
  type: git
  source:
    paths: [ "bootstrap.py" ]
    branch: master
    uri: http://github.com/cf-platform-eng/bosh-azure-template.git

- name: s3-release
  type: s3
  source:
    bucket: {{s3-bucket}}
    region_name: us-west-2
    regexp: .*-v(?P<version>.*)\.tgz
    access_key_id: {{s3-access-key}}
    secret_access_key: {{s3-secret}}

jobs:

- name: copy-bootstrap
  plan:
  - get: github-repo
    trigger: true
  - task: copy-bootstrap
    config:
      platform: linux
      image: docker:///alpine
      inputs:
      - name: github-repo
      outputs:
      - name: s3-release
      run:
        path: sh
        args: [ "-c", "cp github-repo/bootstrap.py s3-release" ]
  - put: s3-release
    params:
      from: s3-release/bootstrap.py
 
- name: copy-release
  plan:
  - get: github-release
    trigger: true
  - task: copy-release
    config:
      platform: linux
      image: docker:///alpine
      inputs:
      - name: github-release
      outputs:
      - name: s3-release
      run:
        path: sh
        args: [ "-c", "cp github-release/*.tgz s3-release" ]
  - put: s3-release
    params:
      file: s3-release/*.tgz
  - task: copy-latest
    config:
      platform: linux
      image: docker:///alpine
      inputs:
      - name: github-release
      outputs:
      - name: s3-release
      run:
        path: sh
        args: [ "-c", "cp github-release/*.tgz s3-release/latest.tgz" ]
  - put: s3-release
    params:
      file: s3-release/latest.tgz
  - task: save-version
    config:
      platform: linux
      image: docker:///alpine
      inputs:
      - name: github-release
      outputs:
      - name: s3-release
      run:
        path: sh
        args: [ "-c", "ls github-release/*.tgz | sed 's/github-release\\/.*-//' | sed 's/.tgz//' >s3-release/version.txt" ]
  - put: s3-release
    params:
      file: s3-release/version.txt
